name = "tboir"
display_name = "The Binding of Isaac Repentance"
home = "https://discord.com/channels/731205301247803413/1454262765047775326"
default_url = "https://github.com/NaveTK/Archipelago/releases/download/v{{version}}/tboir.apworld"

[versions]
"0.2.3" = {}
